apiVersion: v1
kind: ServiceAccount
metadata:
  name: borderless-csi-sa
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.secret.csiRoleArn }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: borderless-aws-secrets
  namespace: {{ .Values.namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secret.appSecretName }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: DB_USER
            objectAlias: DB_USER
          - path: DB_PASSWORD
            objectAlias: DB_PASSWORD
  secretObjects:
    - secretName: borderless-secret
      type: Opaque
      data:
        - objectName: DB_USER
          key: DB_USER
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
        - objectName: DB_PASSWORD
          key: POSTGRES_PASSWORD
