apiVersion: v1
kind: Secret
metadata:
  name: borderless-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_USER: {{ .Values.secret.dbUser }}
  DB_PASSWORD: {{ .Values.secret.dbPassword }}
  POSTGRES_PASSWORD: {{ .Values.secret.dbPassword }}
