apiVersion: v1
kind: ConfigMap
metadata:
  name: borderless-config
  namespace: borderless
data:
  DB_HOST: "borderless-postgres-service"
  DB_PORT: "5432"
  DB_NAME: "appdb"
  CORS_ORIGIN: "http://100.58.128.188:8080"
