apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: borderless-postgres-pvc
  namespace: borderless
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
