apiVersion: v1
kind: Secret
metadata:
  name: borderless-secret
  namespace: borderless
type: Opaque
data:
  DB_USER: c3RhbmxleQ==
  DB_PASSWORD: QWJ1YmFrYXIwMDcmQCM=
  POSTGRES_PASSWORD: QWJ1YmFrYXIwMDcmQCM=
